### ISSUE TITLE
Error : Cannot access offset of type string on string

### ISSUE THREAD

**Issue by Zyrfex** [taufik-nurrohman/parsedown-extra-plugin#21]
Hello,

I have a problem with this :
```
<?php
	include('Parsedown.php'); // 1.7.4
	include('ParsedownExtra.php'); // 0.8.1
	include('ParsedownExtraPlugin.php'); // 1.3.2
	
	$Extra = new ParsedownExtraPlugin();
	
	echo $Extra->text('# Test');
?>
```

I have this error :
```
Warning: Only the first byte will be assigned to the string offset in /home/clients/12345/web/lib/parsedown-extra-plugin-1.3.2/ParsedownExtraPlugin.php on line 392
Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /home/clients/12345/web/lib/parsedown-extra-plugin-1.3.2/ParsedownExtraPlugin.php:392 Stack trace: #0 /home/clients/12345/web/lib/parsedown-extra-plugin-1.3.2/ParsedownExtraPlugin.php(186): ParsedownExtraPlugin->doSetContent(Array, NULL, false, 'argument', Array) #1 /home/clients/12345/web/lib/parsedown-1.7.4/Parsedown.php(232): ParsedownExtraPlugin->blockHeader(Array, NULL) #2 /home/clients/12345/web/lib/parsedown-1.7.4/Parsedown.php(39): Parsedown->lines(Array) #3 /home/clients/12345/web/lib/parsedown-extra-0.8.1/ParsedownExtra.php(46): Parsedown->text('# Test') #4 /home/clients/12345/web/test.php(9): ParsedownExtra->text('# Test') #5 {main} thrown in /home/clients/12345/web/lib/parsedown-extra-plugin-1.3.2/ParsedownExtraPlugin.php on line 392
```
I use PHP 8.0.

With PHP 7.4 :
```
Warning: Illegal string offset 'argument' in /home/clients/12345/web/lib/parsedown-extra-plugin-1.3.2/ParsedownExtraPlugin.php on line 392
Fatal error: Uncaught Exception: Method Tine does not exists. in /home/clients/12345/web/lib/parsedown-extra-plugin-1.3.2/ParsedownExtraPlugin.php:92 Stack trace: #0 /home/clients/12345/web/lib/parsedown-1.7.4/Parsedown.php(1518): ParsedownExtraPlugin->__call('Tine', Array) #1 /home/clients/12345/web/lib/parsedown-extra-plugin-1.3.2/ParsedownExtraPlugin.php(403): Parsedown->element(Array) #2 /home/clients/12345/web/lib/parsedown-1.7.4/Parsedown.php(297): ParsedownExtraPlugin->element(Array) #3 /home/clients/12345/web/lib/parsedown-1.7.4/Parsedown.php(39): Parsedown->lines(Array) #4 /home/clients/12345/web/lib/parsedown-extra-0.8.1/ParsedownExtra.php(46): Parsedown->text('# Test') #5 /home/clients/12345/web/test.php(9): ParsedownExtra->text('# Test') #6 {main} thrown in /home/clients/12345/web/lib/parsedown-extra-plugin-1.3.2/ParsedownExtraPlugin.php on line 92
```

Thanks.

Regards.

**Comment by Zyrfex** [comment]
Hum...

I use PHP 8.

**Comment by taufik-nurrohman** [comment]
Maybe related: #20

**Comment by Zyrfex** [comment]
Hello,
I just try this (you can see version i have used in include) :
```php
<?php
	include('lib/parsedown-1.7.4/Parsedown.php');
	include('lib/parsedown-extra-0.8.0/ParsedownExtra.php');
	include('lib/parsedown-extra-plugin-1.3.2/ParsedownExtraPlugin.php');
	
	$Extra = new ParsedownExtraPlugin();
	
	echo $Extra->text('# Test');
?>
```

I have this error :
```
Fatal error: Uncaught Exception: Method textElements does not exists. in /home/clients/12345/web/lib/parsedown-extra-plugin-1.3.2/ParsedownExtraPlugin.php:92 Stack trace: #0 /home/clients/12345/web/lib/parsedown-extra-0.8.0/ParsedownExtra.php(46): ParsedownExtraPlugin->__call('textElements', Array) #1 /home/clients/12345/web/test.php(9): ParsedownExtra->text('# Test') #2 {main} thrown in /home/clients/12345/web/lib/parsedown-extra-plugin-1.3.2/ParsedownExtraPlugin.php on line 92
```

Thanks.
Regards.

**Comment by taufik-nurrohman** [comment]
Try Parsedown version 1.8.0.

**Comment by Zyrfex** [comment]
Hello,

Working with this version :
```
<?php
	include('lib/parsedown-1.8.0-beta-6/Parsedown.php');
	include('lib/parsedown-extra-0.8.0/ParsedownExtra.php');
	include('lib/parsedown-extra-plugin-1.3.2/ParsedownExtraPlugin.php');
	
	$Extra = new ParsedownExtraPlugin();
	
	echo $Extra->text('# Test');
?>
```
Thanks.
Regards.
